const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){const window={SPIDEY_APPROVED_ART_MASTER:{},SPIDEY_PREVIEW_ART:{},SpideyFlyCore:{eligible:e=>e.category==='spotlight_hour'}};const context={URL,window,document:{readyState:'loading',addEventListener(){}},spideyCategoryLabel:e=>e.category,formatRange:()=> '28/09, 01:30 → 01/10, 11:30'};vm.createContext(context);vm.runInContext(fs.readFileSync('spidey-app/preview-art.js','utf8'),context);window.SPIDEY_PREVIEW_ART={};vm.runInContext(fs.readFileSync('spidey-app/player-ui.js','utf8'),context);return window}
test('FLY event panel retains distinct bonuses, Pokémon, notes, source and local date',()=>{const w=setup(),e={id:'seedot',title:'Spotlight Hour: Seedot',category:'spotlight_hour',summary:'2× PE por captura.',bonuses:['2× PE por captura.','Mais encontros.'],pokemon:[{name:'Seedot',note:'na natureza'}],notes:['Sem bônus de shiny anunciado.'],source:{name:'Comunidade',url:'https://pokemongohub.net/event'},schedule:{start_local:'2026-10-01T18:00:00-03:00',end_local:'2026-10-01T19:00:00-03:00'}};const html=w.SpideyPlayer.panel(e,{fly:true});for(const value of ['2× PE por captura.','Mais encontros.','Seedot — na natureza','Sem bônus de shiny anunciado.','Informação da comunidade','01/10 · 18:00 → 19:00'])assert.ok(html.includes(value),value);assert.equal(html.split('2× PE por captura.').length,2)});
test('regional multi-day time uses Brazil conversion, never labels original local hours as Brazil',()=>{const w=setup();assert.equal(w.SpideyPlayer.time({category:'regional_event',schedule:{start_local:'2026-09-28T10:00',end_local:'2026-10-01T20:00'}}),'28/09, 01:30 → 01/10, 11:30 (Brasília)')});
test('approved binary outranks a preview illustration; preview never grants approval',()=>{const w=setup();w.SPIDEY_APPROVED_ART_MASTER.x={file:'approved.avif',sha256:'abc'};w.SPIDEY_PREVIEW_ART.x={file:'draft.png',sha256:'def'};assert.equal(w.SpideyPlayer.art({id:'x'}),'approved.avif?v=abc');assert.ok(!w.SpideyPlayer.image({id:'x',title:'Xerneas'}).includes('player-art-window'));assert.equal(Object.keys(w.SPIDEY_APPROVED_ART_MASTER).length,1)});

test('unavailable approved binary does not fall through to a competing preview',()=>{const w=setup();w.SPIDEY_APPROVED_ART_MASTER.x={file:'broken.avif',sha256:'abc'};w.SPIDEY_PREVIEW_ART.x={file:'draft.png',sha256:'def'};w.SPIDEY_UNAVAILABLE_ART={'broken.avif':'TRUNCATED_CONTAINER'};assert.equal(w.SpideyPlayer.art({id:'x'}),null);assert.equal(w.SpideyPlayer.image({id:'x'}),'')});

test('explicit correction draft restores an unavailable asset only in preview without changing master',()=>{const w=setup();const a={file:'broken.avif',sha256:'abc'};w.SPIDEY_APPROVED_ART_MASTER.x=a;w.SPIDEY_UNAVAILABLE_ART={'broken.avif':'TRUNCATED_CONTAINER'};w.SPIDEY_PREVIEW_ART.x={file:'review.png',sha256:'def',status:'PENDING_REVIEW',display:'full_poster',restoresUnavailableArt:'broken.avif'};assert.equal(w.SpideyPlayer.art({id:'x'}),'review.png?v=def');assert.equal(w.SPIDEY_APPROVED_ART_MASTER.x,a);assert.ok(!w.SpideyPlayer.image({id:'x'}).includes('player-art-window'))});
