(() => {
  'use strict';
  const VERSION = 'spidey-app-v2.3-20260929.5-coverage-aware';
  const TECHNICAL_ART = /\/assets\/events\/generated\//i;
  let scheduled = false;
  function contextText(img) { const owner = img.closest('[data-v22-event], .event-card, .experience-mini, .experience-feature, .weekly-item, #eventDetail'); return `${img.alt || ''} ${owner?.textContent || ''}`; }
  function isKnownBrokenPublicArt(img) { const src = String(img?.currentSrc || img?.src || ''); return !window.isSpideyApprovedImage?.(src) && /festival[- ]das[- ]luzes|festival of lights/i.test(`${src} ${contextText(img)}`); }
  function coverageOwner(img) { const owner = img?.closest?.('[data-v22-event], .event-card, .experience-mini, .experience-feature, .weekly-item, #eventDetail'); return owner?.querySelector?.('.spidey-cover-art') ? owner : null; }
  function collapseArt(img, reason = 'unavailable') { if (!img) return; if (img.hidden !== true) img.hidden = true; img.classList.add('v23-hidden-art'); img.dataset.v23ArtReason = reason; const covered = coverageOwner(img); if (covered) { covered.classList.remove('v23-no-art', 'v23-no-hero'); covered.closest('.experience-feature')?.classList.remove('v23-no-art'); return; } img.closest('#eventDetail')?.classList.add('v23-no-hero'); img.closest('.experience-mini')?.classList.add('v23-no-art'); img.closest('.experience-feature')?.classList.add('v23-no-art'); img.closest('.event-card')?.classList.add('v23-no-art'); img.closest('.weekly-item')?.classList.add('v23-no-art'); img.closest('[data-v22-event]')?.classList.add('v23-no-art'); }
  function restoreArt(img) { if (!img || TECHNICAL_ART.test(String(img.currentSrc || img.src || '')) || isKnownBrokenPublicArt(img)) return; if (img.hidden !== false) img.hidden = false; img.classList.remove('v23-hidden-art'); delete img.dataset.v23ArtReason; const detail = img.closest('#eventDetail'); if (detail && !detail.querySelector('.detail-hero.v23-hidden-art')) detail.classList.remove('v23-no-hero'); img.closest('.experience-mini')?.classList.remove('v23-no-art'); img.closest('.experience-feature')?.classList.remove('v23-no-art'); img.closest('.event-card')?.classList.remove('v23-no-art'); img.closest('.weekly-item')?.classList.remove('v23-no-art'); img.closest('[data-v22-event]')?.classList.remove('v23-no-art'); }
  function guardImage(img) { if (!img) return; const src = String(img.currentSrc || img.src || ''); if (!src || TECHNICAL_ART.test(src)) { collapseArt(img, 'technical-fallback'); return; } if (isKnownBrokenPublicArt(img)) { collapseArt(img, 'blocked-public-art'); return; } if (img.dataset.v23Guarded !== '1') { img.dataset.v23Guarded = '1'; img.addEventListener('error', () => collapseArt(img, 'load-error')); img.addEventListener('load', () => { const loadedSrc = String(img.currentSrc || img.src || ''); if (TECHNICAL_ART.test(loadedSrc) || !img.naturalWidth || isKnownBrokenPublicArt(img)) collapseArt(img, 'invalid-load'); else restoreArt(img); }); } if (img.complete) { if (!img.naturalWidth) collapseArt(img, 'empty-image'); else restoreArt(img); } }
  function guardPublicArt(root = document) { root.querySelectorAll?.('.detail-hero, .experience-feature-art, .experience-mini img:not(.spidey-cover-pokemon), .event-thumb, .v22-event-art, .weekly-item img:not(.spidey-cover-pokemon)').forEach(guardImage); }
  function compactWeeklyWithoutArt(root = document) { root.querySelectorAll?.('.weekly-item').forEach((card) => { const image = card.querySelector('img:not(.spidey-cover-pokemon)'); const coverage = card.querySelector('.spidey-cover-art'); const usable = Boolean(coverage || (image && !image.hidden && !image.classList.contains('v23-hidden-art'))); card.classList.toggle('v23-no-art', !usable); }); }
  function hideInternalStats() { const artStat = document.querySelector('#weeklyArtCount')?.parentElement; if (!artStat) return; artStat.hidden = true; artStat.classList.add('v23-internal-stat'); }
  function hideLegacyFeedWhenMonthBoardExists() { const board = document.querySelector('#monthBoardV22'); const feedSection = document.querySelector('#eventList')?.closest('.section'); if (!feedSection) return; feedSection.classList.toggle('v23-legacy-feed', Boolean(board)); }
  function hideInternalStampNotes(root = document) { root.querySelectorAll?.('.stamp-detail-v2 h3').forEach((heading) => { if (heading.textContent.trim() !== 'Observações') return; heading.hidden = true; const notes = heading.nextElementSibling; if (notes?.matches('.bonus-list')) notes.hidden = true; }); root.querySelectorAll?.('.stamp-detail-v2 li, .stamp-detail-v2 p').forEach((el) => { if (/Piloto SPS|Updated exact coords|fonte de cruzamento|revalidar antes de substituir/i.test(el.textContent || '')) if (el.hidden !== true) el.hidden = true; }); }
  function humanizeRemainingCopy(root = document) { root.querySelectorAll?.('.microcopy, p, small, span, .map-location-type').forEach((el) => { if (el.children.length) return; const text = el.textContent.trim(); if (!text) return; if (/visual autom[aá]tico|arte premium ainda n[aã]o dispon[ií]vel|conte[uú]do factual|curadoria autom[aá]tica/i.test(text)) { if (el.hidden !== true) el.hidden = true; return; } if (/^GPX indispon[ií]vel:/i.test(text)) { el.textContent = 'Sem rota GPX para este evento.'; return; } if (text === 'Permissão de notificações ativada.') { el.textContent = 'Notificações ativadas.'; return; } if (el.classList.contains('map-location-type') && text === 'STAMP') el.textContent = 'SELO'; }); }
  function apply() { scheduled = false; document.body?.classList.add('spidey-app-v2'); document.documentElement.dataset.spideyApp = 'v2.3'; hideLegacyFeedWhenMonthBoardExists(); humanizeRemainingCopy(); hideInternalStampNotes(); hideInternalStats(); guardPublicArt(); compactWeeklyWithoutArt(); }
  function schedule() { if (scheduled) return; scheduled = true; requestAnimationFrame(apply); }
  function init() { apply(); const observer = new MutationObserver((mutations) => { if (mutations.some((m) => m.addedNodes.length || m.type === 'characterData' || (m.type === 'attributes' && m.attributeName === 'src'))) schedule(); }); observer.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ['src'] }); window.addEventListener('spideythemechange', schedule); window.SpideyAppV23 = { version: VERSION, refresh: apply }; }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true }); else init();
})();
