from pathlib import Path

path = Path("bot.py")
text = path.read_text(encoding="utf-8")

if "import time\n" not in text:
    text = text.replace("import os\n", "import os\nimport time\n", 1)

config_anchor = '''NEWS_URL = "https://pokemongo.com/pt-BR/news"\n'''
config_block = '''NEWS_URL = "https://pokemongo.com/pt-BR/news"\nWHAPI_BASE_URL = os.getenv("WHAPI_BASE_URL", "https://gate.whapi.cloud").rstrip("/")\nWHAPI_TOKEN = os.getenv("WHAPI_TOKEN", "").strip()\nWHAPI_CHANNEL_ID = os.getenv("WHAPI_CHANNEL_ID", "").strip()\n'''
if "WHAPI_BASE_URL" not in text:
    if config_anchor not in text:
        raise SystemExit("Ancora de configuracao nao encontrada")
    text = text.replace(config_anchor, config_block, 1)

func_anchor = '''def _botao_whatsapp(token):\n'''
func_block = '''def _whapi_configurado():\n    return bool(WHAPI_TOKEN and WHAPI_CHANNEL_ID)\n\n\ndef _whapi_caption(conteudo):\n    partes = [conteudo["titulo"], conteudo["mensagem_original"]]\n    if conteudo["coordenadas"]:\n        coords = "\\n".join(_coord_crua(lat, lon) for lat, lon in conteudo["coordenadas"])\n        partes.append(f"📍 Coordenadas:\\n{coords}")\n    if conteudo["url"]:\n        partes.append(f"🔗 Fonte: {conteudo['url']}")\n    return "\\n\\n".join(str(p).strip() for p in partes if p).strip()\n\n\ndef _publicar_whapi(conteudo):\n    if not _whapi_configurado():\n        return None\n    imagem_url = str(conteudo.get("imagem_url") or "").strip()\n    if not imagem_url:\n        raise RuntimeError("Imagem publica ausente para publicacao automatica no Canal")\n\n    payload = {\n        "to": WHAPI_CHANNEL_ID,\n        "media": imagem_url,\n        "caption": _whapi_caption(conteudo),\n    }\n    headers = {\n        "Authorization": f"Bearer {WHAPI_TOKEN}",\n        "Content-Type": "application/json",\n        "Accept": "application/json",\n    }\n\n    ultimo_erro = None\n    for espera in (0, 2, 5):\n        if espera:\n            time.sleep(espera)\n        try:\n            resposta = requests.post(\n                f"{WHAPI_BASE_URL}/messages/image",\n                headers=headers,\n                json=payload,\n                timeout=60,\n            )\n            if resposta.status_code >= 500:\n                ultimo_erro = RuntimeError(\n                    f"Whapi HTTP {resposta.status_code}: {resposta.text[:500]}"\n                )\n                continue\n            resposta.raise_for_status()\n            return resposta.json()\n        except (requests.RequestException, ValueError) as erro:\n            ultimo_erro = erro\n\n    raise RuntimeError(f"Falha ao publicar no Canal via Whapi: {ultimo_erro}")\n\n\n'''
if "def _publicar_whapi(" not in text:
    if func_anchor not in text:
        raise SystemExit("Ancora de funcoes WhatsApp nao encontrada")
    text = text.replace(func_anchor, func_block + func_anchor, 1)

old = '''    mensagem_publicada = conteudo["mensagem_original"]\n    if conteudo["gpx_bytes"]:\n        mensagem_publicada += "\\n\\n🗺️ Arquivo GPX anexado."\n\n    preparar_whatsapp = f"{PUBLIC_BASE_URL}/whatsapp?t={token}"\n    mensagem_publicada += (\n        f"\\n\\n📲 [PREPARAR WHATSAPP]({preparar_whatsapp})"\n        f"\\n📢 [ABRIR CANAL SPIDEY](https://whatsapp.com/channel/0029VbDnlXB2f3EI6wqIcW2F)"\n    )\n\n    mandar_discord(\n        f"✅ APROVADO • {conteudo['titulo']}",\n        mensagem_publicada,\n        url=conteudo["url"],\n        imagem_bytes=conteudo["imagem_bytes"],\n        gpx_bytes=conteudo["gpx_bytes"],\n        gpx_nome=conteudo["gpx_nome"],\n        webhook_url=DISCORD_PUBLICADOS_WEBHOOK,\n    )\n    mandar_coordenadas_cruas(conteudo["coordenadas"], webhook_url=DISCORD_PUBLICADOS_WEBHOOK)\n    tokens_processados.add(token_id)\n\n    return _html_resultado(\n        "Publicação aprovada",\n        "O conteúdo foi aprovado e encaminhado para a etapa de publicação do Spidey.",\n        "#57e389",\n    )\n'''
new = '''    if _whapi_configurado():\n        try:\n            resultado_whapi = _publicar_whapi(conteudo)\n        except Exception as erro_whapi:\n            mandar_discord_texto_puro(\n                f"❌ FALHA WHATSAPP • {conteudo['titulo']}\\n{str(erro_whapi)[:1200]}",\n                webhook_url=DISCORD_PUBLICADOS_WEBHOOK,\n            )\n            return _html_resultado(\n                "Falha ao publicar no WhatsApp",\n                "O Spidey não confirmou a publicação no Canal. A aprovação não foi consumida; tente novamente depois da correção.",\n                "#ff5a67",\n            ), 502\n\n        tokens_processados.add(token_id)\n        detalhe = "Imagem + legenda publicadas automaticamente no Canal Spidey Pokémon GO."\n        try:\n            sent_id = ((resultado_whapi or {}).get("sent_message") or {}).get("id")\n            if sent_id:\n                detalhe += f" ID: {sent_id}"\n        except Exception:\n            pass\n        mandar_discord_texto_puro(\n            f"✅ WHATSAPP PUBLICADO • {conteudo['titulo']}\\n{detalhe}\\nhttps://whatsapp.com/channel/0029VbDnlXB2f3EI6wqIcW2F",\n            webhook_url=DISCORD_PUBLICADOS_WEBHOOK,\n        )\n        return _html_resultado(\n            "Publicado no WhatsApp",\n            "A publicação foi enviada automaticamente para o Canal Spidey Pokémon GO com arte e legenda no mesmo post.",\n            "#57e389",\n        )\n\n    mensagem_publicada = conteudo["mensagem_original"]\n    if conteudo["gpx_bytes"]:\n        mensagem_publicada += "\\n\\n🗺️ Arquivo GPX anexado."\n\n    preparar_whatsapp = f"{PUBLIC_BASE_URL}/whatsapp?t={token}"\n    mensagem_publicada += (\n        f"\\n\\n📲 [PREPARAR WHATSAPP]({preparar_whatsapp})"\n        f"\\n📢 [ABRIR CANAL SPIDEY](https://whatsapp.com/channel/0029VbDnlXB2f3EI6wqIcW2F)"\n    )\n\n    mandar_discord(\n        f"✅ APROVADO • {conteudo['titulo']}",\n        mensagem_publicada,\n        url=conteudo["url"],\n        imagem_bytes=conteudo["imagem_bytes"],\n        gpx_bytes=conteudo["gpx_bytes"],\n        gpx_nome=conteudo["gpx_nome"],\n        webhook_url=DISCORD_PUBLICADOS_WEBHOOK,\n    )\n    mandar_coordenadas_cruas(conteudo["coordenadas"], webhook_url=DISCORD_PUBLICADOS_WEBHOOK)\n    tokens_processados.add(token_id)\n\n    return _html_resultado(\n        "Publicação aprovada",\n        "O conteúdo foi aprovado e encaminhado para a etapa de publicação manual porque o gateway automático ainda não está configurado.",\n        "#57e389",\n    )\n'''

if "✅ WHATSAPP PUBLICADO" not in text:
    if old not in text:
        raise SystemExit("Bloco de aprovacao nao encontrado")
    text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
print("OK: modo automatico de publicacao em Canal via Whapi preparado")
